//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.1055.0.
// 

namespace Schukin.UnemployedDataExport
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class TransferData
    {

        private string fileNameField;

        private string fileDescriptionField;

        private System.DateTime createdField;

        private string partNumberField;

        private string recordsNumberField;

        private TransferDataSender senderField;

        private TransferDataRecipient recipientField;

        private TransferDataPerson[] itemsField;

        private decimal versionField;

        /// <remarks/>
        public string FileName
        {
            get { return this.fileNameField; }
            set { this.fileNameField = value; }
        }

        /// <remarks/>
        public string FileDescription
        {
            get { return this.fileDescriptionField; }
            set { this.fileDescriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Created
        {
            get { return this.createdField; }
            set { this.createdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string PartNumber
        {
            get { return this.partNumberField; }
            set { this.partNumberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string RecordsNumber
        {
            get { return this.recordsNumberField; }
            set { this.recordsNumberField = value; }
        }

        /// <remarks/>
        public TransferDataSender Sender
        {
            get { return this.senderField; }
            set { this.senderField = value; }
        }

        /// <remarks/>
        public TransferDataRecipient Recipient
        {
            get { return this.recipientField; }
            set { this.recipientField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Person", IsNullable = false)]
        public TransferDataPerson[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal version
        {
            get { return this.versionField; }
            set { this.versionField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TransferDataSender
    {

        private string idField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        public string Name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tAddress
    {

        private string addressStringField;

        private string addressCodeField;

        private string zipCodeField;

        private string countryField;

        private string territorySubjectField;

        private string districtField;

        private string placeField;

        private string streetField;

        private string houseField;

        private string buildingField;

        private string appartmentField;

        /// <remarks/>
        public string AddressString
        {
            get { return this.addressStringField; }
            set { this.addressStringField = value; }
        }

        /// <remarks/>
        public string AddressCode
        {
            get { return this.addressCodeField; }
            set { this.addressCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ZipCode
        {
            get { return this.zipCodeField; }
            set { this.zipCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Country
        {
            get { return this.countryField; }
            set { this.countryField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TerritorySubject
        {
            get { return this.territorySubjectField; }
            set { this.territorySubjectField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string District
        {
            get { return this.districtField; }
            set { this.districtField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Place
        {
            get { return this.placeField; }
            set { this.placeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Street
        {
            get { return this.streetField; }
            set { this.streetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string House
        {
            get { return this.houseField; }
            set { this.houseField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Building
        {
            get { return this.buildingField; }
            set { this.buildingField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Appartment
        {
            get { return this.appartmentField; }
            set { this.appartmentField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TransferDataRecipient
    {

        private string idField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        public string Name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TransferDataPerson
    {

        private string snilsField;

        private string lastNameField;

        private string firstNameField;

        private string secondNameField;

        private System.DateTime birthDateField;

        private string genderField;

        private tAddress addressBirthField;

        private tAddress addressRegField;

        private tAddress addressFactField;

        private TransferDataPersonIdentityDocuments[] identityDocumentsField;

        private string categoryIdField;

        private string categoryNameField;

        /// <remarks/>
        public string Snils
        {
            get { return this.snilsField; }
            set { this.snilsField = value; }
        }

        /// <remarks/>
        public string LastName
        {
            get { return this.lastNameField; }
            set { this.lastNameField = value; }
        }

        /// <remarks/>
        public string FirstName
        {
            get { return this.firstNameField; }
            set { this.firstNameField = value; }
        }

        /// <remarks/>
        public string SecondName
        {
            get { return this.secondNameField; }
            set { this.secondNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime BirthDate
        {
            get { return this.birthDateField; }
            set { this.birthDateField = value; }
        }

        /// <remarks/>
        public string Gender
        {
            get { return this.genderField; }
            set { this.genderField = value; }
        }

        /// <remarks/>
        public tAddress AddressBirth
        {
            get { return this.addressBirthField; }
            set { this.addressBirthField = value; }
        }

        /// <remarks/>
        public tAddress AddressReg
        {
            get { return this.addressRegField; }
            set { this.addressRegField = value; }
        }

        /// <remarks/>
        public tAddress AddressFact
        {
            get { return this.addressFactField; }
            set { this.addressFactField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IdentityDocuments")]
        public TransferDataPersonIdentityDocuments[] IdentityDocuments
        {
            get { return this.identityDocumentsField; }
            set { this.identityDocumentsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string CategoryId
        {
            get { return this.categoryIdField; }
            set { this.categoryIdField = value; }
        }

        /// <remarks/>
        public string CategoryName
        {
            get { return this.categoryNameField; }
            set { this.categoryNameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TransferDataPersonIdentityDocuments
    {

        private string idField;

        private string nameField;

        private string seriesField;

        private string numberField;

        private System.DateTime issueDateField;

        private bool issueDateFieldSpecified;

        private string issuerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        public string Name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        public string Series
        {
            get { return this.seriesField; }
            set { this.seriesField = value; }
        }

        /// <remarks/>
        public string Number
        {
            get { return this.numberField; }
            set { this.numberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime IssueDate
        {
            get { return this.issueDateField; }
            set { this.issueDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssueDateSpecified
        {
            get { return this.issueDateFieldSpecified; }
            set { this.issueDateFieldSpecified = value; }
        }

        /// <remarks/>
        public string Issuer
        {
            get { return this.issuerField; }
            set { this.issuerField = value; }
        }
    }
}